/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marcelmika.lims.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OpenedConversation service. Represents a row in the &quot;LiferayLIMS_OpenedConversation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.marcelmika.lims.model.impl.OpenedConversationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.marcelmika.lims.model.impl.OpenedConversationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OpenedConversation
 * @see com.marcelmika.lims.model.impl.OpenedConversationImpl
 * @see com.marcelmika.lims.model.impl.OpenedConversationModelImpl
 * @generated
 */
public interface OpenedConversationModel extends BaseModel<OpenedConversation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a opened conversation model instance should use the {@link OpenedConversation} interface instead.
	 */

	/**
	 * Returns the primary key of this opened conversation.
	 *
	 * @return the primary key of this opened conversation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this opened conversation.
	 *
	 * @param primaryKey the primary key of this opened conversation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ocid of this opened conversation.
	 *
	 * @return the ocid of this opened conversation
	 */
	public long getOcid();

	/**
	 * Sets the ocid of this opened conversation.
	 *
	 * @param ocid the ocid of this opened conversation
	 */
	public void setOcid(long ocid);

	/**
	 * Returns the user ID of this opened conversation.
	 *
	 * @return the user ID of this opened conversation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this opened conversation.
	 *
	 * @param userId the user ID of this opened conversation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this opened conversation.
	 *
	 * @return the user uuid of this opened conversation
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this opened conversation.
	 *
	 * @param userUuid the user uuid of this opened conversation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the conversation ID of this opened conversation.
	 *
	 * @return the conversation ID of this opened conversation
	 */
	@AutoEscape
	public String getConversationId();

	/**
	 * Sets the conversation ID of this opened conversation.
	 *
	 * @param conversationId the conversation ID of this opened conversation
	 */
	public void setConversationId(String conversationId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(OpenedConversation openedConversation);

	public int hashCode();

	public CacheModel<OpenedConversation> toCacheModel();

	public OpenedConversation toEscapedModel();

	public String toString();

	public String toXmlString();
}