/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.marcelmika.lims.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.marcelmika.lims.model.Settings;
import com.marcelmika.lims.model.SettingsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Settings service. Represents a row in the &quot;LiferayLIMS_Settings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.marcelmika.lims.model.SettingsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SettingsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SettingsImpl
 * @see com.marcelmika.lims.model.Settings
 * @see com.marcelmika.lims.model.SettingsModel
 * @generated
 */
public class SettingsModelImpl extends BaseModelImpl<Settings>
	implements SettingsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a settings model instance should use the {@link com.marcelmika.lims.model.Settings} interface instead.
	 */
	public static final String TABLE_NAME = "LiferayLIMS_Settings";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sid", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "status", Types.VARCHAR },
			{ "activeRoomType", Types.VARCHAR },
			{ "activePanelId", Types.VARCHAR },
			{ "mute", Types.BOOLEAN },
			{ "chatEnabled", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table LiferayLIMS_Settings (sid LONG not null primary key,userId LONG,status VARCHAR(75) null,activeRoomType VARCHAR(75) null,activePanelId VARCHAR(75) null,mute BOOLEAN,chatEnabled BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table LiferayLIMS_Settings";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.marcelmika.lims.model.Settings"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.marcelmika.lims.model.Settings"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.marcelmika.lims.model.Settings"),
			true);
	public static long STATUS_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.marcelmika.lims.model.Settings"));

	public SettingsModelImpl() {
	}

	public long getPrimaryKey() {
		return _sid;
	}

	public void setPrimaryKey(long primaryKey) {
		setSid(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_sid);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Settings.class;
	}

	public String getModelClassName() {
		return Settings.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("sid", getSid());
		attributes.put("userId", getUserId());
		attributes.put("status", getStatus());
		attributes.put("activeRoomType", getActiveRoomType());
		attributes.put("activePanelId", getActivePanelId());
		attributes.put("mute", getMute());
		attributes.put("chatEnabled", getChatEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long sid = (Long)attributes.get("sid");

		if (sid != null) {
			setSid(sid);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String activeRoomType = (String)attributes.get("activeRoomType");

		if (activeRoomType != null) {
			setActiveRoomType(activeRoomType);
		}

		String activePanelId = (String)attributes.get("activePanelId");

		if (activePanelId != null) {
			setActivePanelId(activePanelId);
		}

		Boolean mute = (Boolean)attributes.get("mute");

		if (mute != null) {
			setMute(mute);
		}

		Boolean chatEnabled = (Boolean)attributes.get("chatEnabled");

		if (chatEnabled != null) {
			setChatEnabled(chatEnabled);
		}
	}

	public long getSid() {
		return _sid;
	}

	public void setSid(long sid) {
		_sid = sid;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	public String getActiveRoomType() {
		if (_activeRoomType == null) {
			return StringPool.BLANK;
		}
		else {
			return _activeRoomType;
		}
	}

	public void setActiveRoomType(String activeRoomType) {
		_activeRoomType = activeRoomType;
	}

	public String getActivePanelId() {
		if (_activePanelId == null) {
			return StringPool.BLANK;
		}
		else {
			return _activePanelId;
		}
	}

	public void setActivePanelId(String activePanelId) {
		_activePanelId = activePanelId;
	}

	public boolean getMute() {
		return _mute;
	}

	public boolean isMute() {
		return _mute;
	}

	public void setMute(boolean mute) {
		_mute = mute;
	}

	public boolean getChatEnabled() {
		return _chatEnabled;
	}

	public boolean isChatEnabled() {
		return _chatEnabled;
	}

	public void setChatEnabled(boolean chatEnabled) {
		_chatEnabled = chatEnabled;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Settings.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Settings toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Settings)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SettingsImpl settingsImpl = new SettingsImpl();

		settingsImpl.setSid(getSid());
		settingsImpl.setUserId(getUserId());
		settingsImpl.setStatus(getStatus());
		settingsImpl.setActiveRoomType(getActiveRoomType());
		settingsImpl.setActivePanelId(getActivePanelId());
		settingsImpl.setMute(getMute());
		settingsImpl.setChatEnabled(getChatEnabled());

		settingsImpl.resetOriginalValues();

		return settingsImpl;
	}

	public int compareTo(Settings settings) {
		long primaryKey = settings.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Settings settings = null;

		try {
			settings = (Settings)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = settings.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SettingsModelImpl settingsModelImpl = this;

		settingsModelImpl._originalUserId = settingsModelImpl._userId;

		settingsModelImpl._setOriginalUserId = false;

		settingsModelImpl._originalStatus = settingsModelImpl._status;

		settingsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Settings> toCacheModel() {
		SettingsCacheModel settingsCacheModel = new SettingsCacheModel();

		settingsCacheModel.sid = getSid();

		settingsCacheModel.userId = getUserId();

		settingsCacheModel.status = getStatus();

		String status = settingsCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			settingsCacheModel.status = null;
		}

		settingsCacheModel.activeRoomType = getActiveRoomType();

		String activeRoomType = settingsCacheModel.activeRoomType;

		if ((activeRoomType != null) && (activeRoomType.length() == 0)) {
			settingsCacheModel.activeRoomType = null;
		}

		settingsCacheModel.activePanelId = getActivePanelId();

		String activePanelId = settingsCacheModel.activePanelId;

		if ((activePanelId != null) && (activePanelId.length() == 0)) {
			settingsCacheModel.activePanelId = null;
		}

		settingsCacheModel.mute = getMute();

		settingsCacheModel.chatEnabled = getChatEnabled();

		return settingsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{sid=");
		sb.append(getSid());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", activeRoomType=");
		sb.append(getActiveRoomType());
		sb.append(", activePanelId=");
		sb.append(getActivePanelId());
		sb.append(", mute=");
		sb.append(getMute());
		sb.append(", chatEnabled=");
		sb.append(getChatEnabled());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.marcelmika.lims.model.Settings");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sid</column-name><column-value><![CDATA[");
		sb.append(getSid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activeRoomType</column-name><column-value><![CDATA[");
		sb.append(getActiveRoomType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activePanelId</column-name><column-value><![CDATA[");
		sb.append(getActivePanelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mute</column-name><column-value><![CDATA[");
		sb.append(getMute());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chatEnabled</column-name><column-value><![CDATA[");
		sb.append(getChatEnabled());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Settings.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Settings.class
		};
	private long _sid;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _status;
	private String _originalStatus;
	private String _activeRoomType;
	private String _activePanelId;
	private boolean _mute;
	private boolean _chatEnabled;
	private long _columnBitmask;
	private Settings _escapedModelProxy;
}